### PR TITLE
0.5.1 Dev Bug Fixes

### PR DESCRIPTION
**Pull request by j0shuaS**
idk..pull request ig

### CODE REVIEW

**Comment by Emmet-v15** [comment]
@planet-exe if you would like this to be merged into the main project, you will have to make sure that no functionality is removed from branch 5.0.0 and 5.0.1 since you used an outdated version of the project for your update

**Comment by thewander02** [comment]
@planet-exe Converting to a draft until ready once you have made you changes work with the current `dev` branch feel free to try again if you have any questions ask any of the core members 👍

**Comment by j0shuaS** [comment]
huh? u saying that when i added to the project i was a version behind, so now this stuff isnt useful?

**Comment by Emmet-v15** [comment]
Yes, but if you can manage to merge the changes into the dev branch and resolve any conflicts, it can still be added

**Comment by j0shuaS** [comment]
ok ill try

**Comment by j0shuaS** [comment]
i need push acess to dev branch DDDD:

**Comment by Emmet-v15** [comment]
No, you need to update this branch, then we will push it for you

**Pull request closed without merging**
