### PR TITLE
Add Quickstart Guide :)

### PR DESCRIPTION
**Pull request by thewander02**

### CODE REVIEW

**Comment by Emmet-v15** [comment]
This is a great initial guide for now, I've added some changes which you can review

**Comment by thewander02** [comment]
made my changes and everything seems fine to me you made some good changes tho its really been improved good guide for people wanting to commit

**Review by Emmet-v15 — APPROVED** [review]
LGTM!

**Review by Emmet-v15 — APPROVED** [review]
Added a reccomended tag to the stable branch

**Review by Emmet-v15 — APPROVED** [review]

**Review by Emmet-v15 — APPROVED** [review]

**Pull request merged**
